### ISSUE TITLE
Issue on databricks community edition, getting an fsPath error when trying to upload the 1.6million tweets CSV at 223mb.

### ISSUE THREAD

**Issue by sealuwee** [lambda-labs-13-stock-price-2/preprocessing-pipeline#1]
https://trello.com/c/Bix9DmE6/40-issue-on-databricks-community-edition-getting-an-fspath-error-when-trying-to-upload-the-16million-tweets-csv-at-223mb

**Comment by colejhudson** [comment]
Problem:
 - File was too large for DataBricks

Solution:
 - Upload to S3 and link the S3 bucket to DataBricks

**Comment by colejhudson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue on databricks community edition, getting an fsPath error when trying to upload the 1.6million tweets CSV at 223mb.](https://trello.com/c/Bix9DmE6/40-issue-on-databricks-community-edition-getting-an-fspath-error-when-trying-to-upload-the-16million-tweets-csv-at-223mb)
